name: stateful_view_model_widget
description: MVVM
version: 0.1.0
homepage: https://github.com/tikkrapp/stateful_view_model
author: Tikkr <info@tikkr.app>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  stateful_view_model:
    git:
      url: git://github.com/tikkrapp/stateful_view_model.git

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
